include:
  - path: 
      - ./node-compose.yml
      - ./wallet-compose.yml
      - ./mongo-compose.yml
      - ./dpops-compose.yml
services:
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    networks:
      - xcash-network
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal-xcash:-all
      AUTOHEAL_INTERVAL: "20"

networks:
  xcash-network:
    driver: bridge