include:
  - path: 
      - ./node-compose.yml
      - ./wallet-compose.yml
      - ./mongo-compose.yml
      - ./dpops-compose.yml
services:
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    restart: unless-stopped
    networks:
      - xcash-network
    environment:
      AUTOHEAL_CONTAINER_LABEL: "${AUTOHEAL_CONTAINER_LABEL:-all}"
      AUTOHEAL_INTERVAL: "20"


networks:
  xcash-network:
    driver: bridge