services:
  xcash-dpops:
    image: xcashtech/xcash-dpops:latest
    container_name: xcash-dpops
    ports:
      - "18283:18283"
    networks:
      - xcash-network
    volumes:
      - ../../data:/data
    depends_on:
      xcash-node:
        condition: service_healthy
      xcash-wallet:
        condition: service_healthy
      mongodb:
          condition: service_healthy
    environment:
      - NODE_SEC_KEY=${NODE_SEC_KEY}
    command: [
      "./xcash-dpops",
      "--block-verifiers-secret-key", "${NODE_SEC_KEY}",
      "--xcash-daemon-ip-address", "xcash-node",
      "--xcash-wallet-ip-address", "xcash-wallet",
      "--mongodb-uri", "mongodb://mongodb:27017",
      "--server-log-file", "/data/logs/dpops-server.log",
      "--total-threads", "4"
    ]

    healthcheck:
      test: ["CMD", "/bin/bash", "./dpops-check.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: always
