services:
  mongodb:
    image: mongo:4
    container_name: mongo
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - xcash-network
    volumes:
      - ../../data/mongo/db:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always
